### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rjocoleman** [convox/docs#1]
@ddollar @mattmanning @nzoschke 

Features:

* Dynamic ToC based on `/data/toc.yml`
* ready for deployment to GH pages
* Similar look/feel
* All docs pages are in markdown format. 
* Sorting of ToC items on each page (frontmatter).
* Customisable titles.
* Same URLs as readme.io
* Google Analytics
* Intercom embed (untested, ripped from existing docs)
* Support for styled callouts (html) with nested markdown directly in markdown:

```
<div class="block-callout block-show-callout type-warning">
### Cost Management

The Convox Installer by default provisions an Elastic Load Balancer and 3 t2.small instances, giving you 6GB of memory capacity. This runs the Convox API and Private Registry, and leaves room for 10 512MB containers.

This configuration costs $85/month according to the [AWS simple cost calculator](http://calculator.s3.amazonaws.com/index.html).

Each deployed app will provision an additional ELB which starts at $18/month.

At any time you can [uninstall Convox](/getting-started/uninstall-convox) to delete the resources and stop accruing costs.
</div>
```

The following Readme.io features are missing:

- [ ] Search (https://swiftype.com/site-search is easy - it can be seen here https://middlemanapp.com/basics/install/, Google Custom Site Search is another option)
- [ ] Versions: I have some half baked code for scoping everything by version but it's not ready yet - I'm uncertain if this is a critical feature.

Loose ends

- [ ] There's a monkey patch to bring in some nice features to allow docs to be 100% markdown (rather than erb, or haml or whatever). I should extract this.
- [ ] There's no content on the index page.
- [ ] https://docs.convox.com/docs/support is missing.

I'm happy to take feedback and adjust on this, I've detailed the deployment in the quick README.
(set a `.env` with google analytics codes, `$ rake publish`) 

Features:

* Dynamic ToC based on `/data/toc.yml`

**Comment by rjocoleman** [comment]
To preview it the simplest way is:
```
# clone
$ bundle
$ bundle exec middleman
$ open http://localhost:4567/
```
